# Generated by Django 2.0.2 on 2018-03-09 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(blank=True, choices=[('UNPAID', 'unpaid'), ('PAID', 'paid')], max_length=15, null=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now=True)),
                ('cargo_material', models.CharField(max_length=225)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('cargo_weight', models.IntegerField()),
                ('pickup_address', models.CharField(max_length=225)),
                ('pickup_location', models.CharField(blank=True, choices=[('accra', 'ACCRA'), ('kumasi', 'KUMASI'), ('tema', 'TEMA'), ('tamale', 'TAMALE'), ('tokoradi', 'SEKONDI-TAKORADI'), ('cape_coast', 'CAPE COAST'), ('teshie', 'TESHIE'), ('sunyani', 'SUNYANI')], default='accra', help_text='Pickup Location', max_length=100, null=True)),
                ('destination_address', models.CharField(max_length=225)),
                ('destination_location', models.CharField(blank=True, choices=[('accra', 'ACCRA'), ('kumasi', 'KUMASI'), ('tema', 'TEMA'), ('tamale', 'TAMALE'), ('tokoradi', 'SEKONDI-TAKORADI'), ('cape_coast', 'CAPE COAST'), ('teshie', 'TESHIE'), ('sunyani', 'SUNYANI')], default='tema', help_text='Delivery Location', max_length=100, null=True)),
                ('order_notes', models.TextField()),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shipment',
                'verbose_name_plural': 'shipments',
                'ordering': ['order_date'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipper.Shipment'),
        ),
    ]
