# Generated by Django 2.0.2 on 2018-03-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
