# Generated by Django 2.0.2 on 2018-03-11 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(default='full name', max_length=50)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('driver_license', models.CharField(max_length=15, unique=True)),
                ('join_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'driver',
                'verbose_name_plural': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='DriverAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='frontend.Driver')),
            ],
            options={
                'verbose_name': 'driver address',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shipper', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('owner_name', models.CharField(default='owner name', max_length=50)),
                ('company_name', models.CharField(default='company name', max_length=50)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('join_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'shipper',
                'verbose_name_plural': 'shippers',
            },
        ),
        migrations.CreateModel(
            name='ShipperAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippers', to='frontend.Shipper')),
            ],
            options={
                'verbose_name': 'shipper address',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
