# Generated by Django 2.0.2 on 2018-03-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='driver',
            name='join_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
